language: rust

cache: cargo

rust:
  - nightly
  - beta
  - stable

# Dependencies of kcov, used by coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libbfd-dev
      - cmake
    sources:
      - kalakris-cmake

before_install:
  - export ROOT_PATH=`pwd`
  - wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.0.0_1.0.2g-1ubuntu4.6_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-dev_1.0.2g-1ubuntu4.6_amd64.deb
  - sudo dpkg -i libssl1.0.0_1.0.2g-1ubuntu4.6_amd64.deb
  - sudo dpkg -i libssl-dev_1.0.2g-1ubuntu4.6_amd64.deb

matrix:
  allow_failures:
    - rust: nightly

