[package]
name = "addupstream"
version = "0.1.0"
authors = ["Pierre Zemb <contact@pierrezemb.fr>"]

[dependencies]
clap = "~2.19.0"
git2 = "0.6"
regex = "0.2"
hyper = "0.10.9"
hyper-native-tls = "0.2.2"
serde = "1.0.2"
serde_derive = "1.0.2"
serde_json = "1.0.1"