[package]
name = "addupstream"
version = "0.2.0"
authors = ["Pierre Zemb <contact@pierrezemb.fr>"]

[dependencies]
structopt = "0.2"
git2 = "0.7.1"
log = "0.4.1"
regex = "0.2.10"
reqwest = "0.8.5"
serde = "1.0.42"
serde_json = "1.0"
simple-error = "0.1.11"