[package]
name = "addupstream"
version = "0.2.2"
authors = ["Pierre Zemb <contact@pierrezemb.fr>"]

[dependencies]
structopt = "0.2"
git2 = "0.7"
log = "0.4"
regex = "1.0"
reqwest = "0.8"
serde = "1.0"
serde_json = "1.0"
simple-error = "0.1.11"